In [1]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.linear_model import LinearRegression

In [4]:
data_train = np.genfromtxt("train.csv", delimiter=",")

In [34]:
x = pd.read_csv("train.csv")
y = x["Y"]
x.drop("Y", axis = 1, inplace = True)
x

,# age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,-0.049105,-0.044642,0.160855,-0.046985,-0.029088,-0.019790,-0.047082,0.034309,0.028017,0.011349
1,-0.070900,0.050680,-0.089197,-0.074528,-0.042848,-0.025739,-0.032356,-0.002592,-0.012908,-0.054925
2,0.001751,-0.044642,-0.070875,-0.022885,-0.001569,-0.001001,0.026550,-0.039493,-0.022512,0.007207
3,0.048974,0.050680,0.081097,0.021872,0.043837,0.064134,-0.054446,0.071210,0.032433,0.048628
4,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014956,0.011349
...,...,...,...,...,...,...,...,...,...,...
326,0.012648,-0.044642,-0.020218,-0.015999,0.012191,0.021233,-0.076536,0.108111,0.059881,-0.021788
327,0.019913,-0.044642,-0.057941,-0.057314,-0.001569,-0.012587,0.074412,-0.039493,-0.061177,-0.075636
328,0.023546,-0.044642,0.070319,0.025315,-0.034592,-0.014466,-0.032356,-0.002592,-0.019197,-0.009362
329,0.016281,0.050680,0.072474,0.076958,-0.008449,0.005575,-0.006584,-0.002592,-0.023645,0.061054
330,-0.009147,0.050680,-0.030996,-0.026328,-0.011201,-0.001001,-0.021311,-0.002592,0.006209,0.027917

In [35]:
y

0      346.0
1      104.0
2       49.0
3      180.0
4      110.0
       ...
326    233.0
327     63.0
328    288.0
329    131.0
330     42.0
Name: Y, Length: 331, dtype: float64

In [36]:
data_test = np.genfromtxt("test.csv", delimiter=",")

In [44]:
x_test_original = pd.read_csv("test.csv")
x_test.columns = ["# age", "sex", "bmi","bp", "s1", "s2", "s3", "s4", "s5", "s6"]
x_test

,# age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,-0.078165,-0.044642,-0.073030,-0.057314,-0.084126,-0.074277,-0.024993,-0.039493,-0.018118,-0.083920
1,-0.030942,0.050680,0.001339,-0.005671,0.064477,0.049416,-0.047082,0.108111,0.083797,0.003064
2,-0.005515,0.050680,0.001339,-0.084857,-0.011201,-0.016658,0.048640,-0.039493,-0.041180,-0.088062
3,-0.020045,-0.044642,-0.084886,-0.026328,-0.035968,-0.034194,0.041277,-0.051671,-0.082381,-0.046641
4,-0.034575,-0.044642,-0.037463,-0.060757,0.020446,0.043466,-0.013948,-0.002592,-0.030751,-0.071494
...,...,...,...,...,...,...,...,...,...,...
105,0.009016,0.050680,0.069241,0.059744,0.017694,-0.023234,-0.047082,0.034309,0.103292,0.073480
106,0.005383,-0.044642,0.049840,0.097616,-0.015328,-0.016345,-0.006584,-0.002592,0.017037,-0.013504
107,0.009016,-0.044642,-0.012673,0.028758,-0.018080,-0.005072,-0.047082,0.034309,0.023375,-0.005220
108,0.019913,-0.044642,-0.034229,0.055153,0.067229,0.074155,-0.006584,0.032833,0.024725,0.069338
109,0.016281,0.050680,0.009961,-0.043542,-0.096510,-0.094632,-0.039719,-0.039493,0.017037,0.007207

In [37]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y)

In [38]:
algo1 = LinearRegression()

In [39]:
algo1.fit(x_train, y_train)

LinearRegression()

In [41]:
score_test = algo1.score(x_test, y_test)
score_train = algo1.score(x_train, y_train)
print(score_train, score_test)

0.4701708872182382 0.5206840004535511

In [45]:
y_pred = algo1.predict(x)
y_pred

array([247.36138665,  66.0409736 , 101.30952737, 213.35597083,
       159.7877695 ,  76.03995096, 168.70981941, 173.3951761 ,
        52.56615012, 225.97509583, 104.77348896,  89.3516685 ,
       126.58347622,  63.82610145, 149.9520369 , 142.09130754,
        68.61905253, 103.78005601, 193.3648407 , 103.81280602,
       125.72808221, 159.92936437,  93.36835903,  79.29295543,
        76.15428837, 155.44644607, 188.84864549, 127.25849013,
       233.51350051, 145.20264201,  55.58071504, 168.45837923,
       101.70809062, 119.7952723 , 149.94640827, 228.67271302,
       183.37800681,  91.50169205, 160.46180787, 204.81239598,
       161.5230006 , 135.2159495 ,  37.96897561, 109.07586272,
       128.83030848, 212.14323782, 231.98194249, 137.19414352,
       174.37258639,  82.55340794, 150.81753095,  83.6936816 ,
       197.03909058, 148.74683369, 162.48855915, 139.12554984,
       171.34721959, 153.78597887, 211.69073068, 108.06882282,
       138.14597235, 162.2246798 ,  61.87115815, 231.57653762,
       139.71324117, 127.74427528, 138.78073147, 171.80452821,
       170.08427074, 119.33621789, 109.48369633, 156.20527996,
       133.96277039, 220.63088517, 134.20322331, 105.70526368,
       256.17224078, 185.53790214, 196.59582695, 187.98154755,
       197.20520479, 154.06429743,  87.19402711, 186.33854067,
       112.09357445, 128.97848806,  67.61978093,  68.83411375,
       144.7138174 , 133.53300392, 194.76743524,  81.88212488,
        53.65624858, 199.77526072, 115.40523907, 105.98642615,
       232.52578308, 201.29127592, 231.9981121 , 151.79769443,
        64.55674113, 104.20740137, 183.07930177, 184.69191866,
       114.7947521 ,  59.19388059,  94.71685921, 112.80669344,
       148.50557995, 125.2452317 , 214.55278192,  50.76196185,
       189.23329223, 185.92440324, 150.75871893,  70.15942574,
       233.46347443, 180.02722699,  99.55472813, 173.24687602,
       222.3845361 , 190.93169312, 168.91310365, 185.64894882,
       154.3560755 , 185.72739008, 143.64277998,  96.2067435 ,
       172.29107326, 164.13682117, 176.65390695, 114.25101129,
       162.17435588,  87.64234699,  96.92818167, 163.98731678,
        80.13801558, 177.4431939 ,  73.85127128, 116.36752689,
        73.39425604, 124.56651387, 131.69160309,  97.22310631,
       201.87526394, 126.72461383, 160.35410066, 152.73471942,
        64.82784312, 213.45391366, 249.44732241, 134.71706481,
       184.87712269, 162.26983063, 158.35453572, 114.81078152,
       146.06860048, 169.21723947, 123.83153146,  93.52496846,
        85.20639055, 243.73054002, 211.04718739, 150.6717731 ,
       139.17216532, 133.31418555,  65.14909358, 192.09923613,
       154.1778292 , 235.30919745,  77.11048838, 167.92714809,
        74.59387123, 182.81625271, 161.21265454, 114.98255365,
       227.91644299, 162.20584707, 116.91653504,  94.64681215,
        66.59897527, 182.70607579, 139.44360487, 157.51885225,
        56.34350543, 282.14783829,  89.7113559 , 127.98402683,
       114.41086045, 167.61662792, 178.88623556, 188.23521734,
       142.28468707, 172.47909243,  89.41733989, 238.34682051,
       280.47520191, 156.74600959,  91.83077933,  45.7103159 ,
        96.69630954, 152.24398898, 116.54573344, 127.00507427,
       154.47252725, 142.65954856,  79.80904831, 112.40011597,
       168.64995225,  86.53540685,  93.69507671, 251.95306235,
       126.13988049, 250.33979339, 103.20073034, 172.10166572,
       131.66744055, 120.75986884, 128.8550358 , 236.88387504,
        85.08829655, 125.79621678, 133.53630145, 175.31969129,
       201.03513011, 161.23710328, 159.38605744, 122.06639841,
        54.33748215, 106.3825295 , 175.03803119, 248.26697255,
       144.68561113, 134.04212273, 182.10665252, 117.52492503,
        73.43622021, 167.59217057, 130.59278429, 251.30958512,
       103.60965629, 224.73370586, 206.37042315, 178.26148279,
       116.77147885,  61.46472113, 163.9083038 , 223.22952302,
       135.30167319, 172.36475212, 228.43017098, 189.17176635,
       209.98465289, 147.68771568, 207.80365617,  70.25950974,
       179.4001615 , 158.04942695, 171.57120929, 134.86385717,
       126.31559369, 167.59586976, 211.60558189, 149.66058941,
       125.89267025, 137.03649942, 152.43813055, 153.71630119,
       110.62707738, 153.44235546, 128.58480102, 113.28789772,
       173.72407785, 221.91364885,  88.86050823, 144.58439663,
       174.21213655,  46.76003272, 205.01340414, 252.15805563,
       115.17053145, 229.48820695, 231.98859243, 108.79628014,
       190.9446406 ,  85.88520227, 175.99439583, 128.43501013,
       121.76124357, 202.87267601, 160.28213491,  65.50815883,
       230.44823948, 157.35442452, 126.33576805, 214.13943725,
        93.08659294, 139.74922476, 205.88805728,  57.27725729,
       195.05963044, 160.47927296, 132.9207355 , 172.07821624,
       237.71931701, 213.5808585 , 105.16991756, 124.93980867,
       102.17817879,  47.41463085, 208.31958724, 118.23454655,
       133.88728179, 120.45211039, 181.73948766, 182.17051687,
       149.59624518, 258.77597702, 177.59385159,  60.32209303,
       116.59465559,  93.24286986,  83.80390584, 199.11882922,
        83.4664659 , 195.93728115, 186.98047593,  62.71172322,
       207.46206857, 196.34935112, 124.47853199])

In [47]:
y_pred = pd.DataFrame(y_pred)

In [49]:
y_pred.to_csv("predicted_value.csv")